# Generated by Django 4.2.7 on 2023-12-01 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CSE', 'COMPUTER SCIENCE AND ENGINEERING'), ('EEE', 'ELECTRICAL ENGINEERING'), ('MECH', 'MECHANICAL ENGINEERING'), ('ECE', 'ELECTRONIC AND COMMUNICATION ENGINEERING'), ('AG', 'AGRICULTURE ENGINEERING')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashfeatures.department')),
            ],
        ),
        migrations.CreateModel(
            name='Semestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashfeatures.department')),
                ('semestar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashfeatures.semestar')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=12)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashfeatures.department')),
                ('subject', models.ManyToManyField(to='dashfeatures.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regd_no', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.SmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashfeatures.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashfeatures.section')),
                ('semestar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashfeatures.semestar')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashfeatures.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashfeatures.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashfeatures.teacher')),
            ],
        ),
    ]
