# Generated by Django 4.2.9 on 2024-01-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_email"),
        ("core", "0002_alter_user_email_forgotpasswordotp"),
    ]

    operations = []
